services:
  # Backend API Service
  - type: web
    name: herculesai-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health

  # Frontend Service
  - type: static
    name: herculesai
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_FLASK_API_URL
        value: https://herculesai-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 